version: '2'

services:
  cryptocurrency-price-api:
    image: naufalfmm/cryptocurrency-price-api:latest
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.app
    container_name: "cryptocurrency-price-api"
    working_dir: /usr/src
    ports:
      - ${PORT}:${PORT}