// Code generated by MockGen. DO NOT EDIT.
// Source: init.go

// Package coins is a generated GoMock package.
package coins

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/naufalfmm/cryptocurrency-price-api/model/dto"
)

// MockUsecases is a mock of Usecases interface.
type MockUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockUsecasesMockRecorder
}

// MockUsecasesMockRecorder is the mock recorder for MockUsecases.
type MockUsecasesMockRecorder struct {
	mock *MockUsecases
}

// NewMockUsecases creates a new mock instance.
func NewMockUsecases(ctrl *gomock.Controller) *MockUsecases {
	mock := &MockUsecases{ctrl: ctrl}
	mock.recorder = &MockUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecases) EXPECT() *MockUsecasesMockRecorder {
	return m.recorder
}

// SyncPrice mocks base method.
func (m *MockUsecases) SyncPrice(ctx context.Context, req dto.SyncCoinPriceRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SyncPrice", ctx, req)
}

// SyncPrice indicates an expected call of SyncPrice.
func (mr *MockUsecasesMockRecorder) SyncPrice(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncPrice", reflect.TypeOf((*MockUsecases)(nil).SyncPrice), ctx, req)
}
