FROM alpine:latest AS build

RUN apk add --no-cache --update go gcc g++

WORKDIR /go/src/github.com/naufalfmm/cryptocurrency-price-api-migration

COPY go.mod go.sum ./
RUN GO111MODULE=on go mod download

COPY /migrations/. ./migrations/.
COPY /consts/. ./consts/.
COPY /utils/. ./utils/.

RUN CGO_ENABLED=1 GOOS=linux go build -C ./migrations/ -a -installsuffix cgo -o cryptocurrency-price-api-migration


FROM alpine:latest

RUN apk update && apk add --no-cache tzdata
RUN apk --no-cache add ca-certificates

WORKDIR /usr/src
COPY --from=build /go/src/github.com/naufalfmm/cryptocurrency-price-api-migration/migrations/cryptocurrency-price-api-migration ./migrations/cryptocurrency-price-api-migration